generator:
  class: IcePropelSecurityGenerator
  param:
    model_class:           iceModelMetaTag
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              iceModelMetaTag
    plural:                iceModelMetaTags
    route_prefix:          ice_model_meta_tag
    with_propel_route:     1
    actions_base_class:    IceBackendActions

    use_security_yaml_credentials: false

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:
        display: [url, parameters, bg_BG, en_US]
      edit:    ~
      new:     ~
