config/breadcrumbs.yml:
  class: sfSimpleYamlConfigHandler
  param:
    prefix: ice_breadcrumbs_

config/seo.yml:
  class: sfSimpleYamlConfigHandler

#modules/*/config/breadcrumbs.yml:
#  class: sfDefineEnvironmentConfigHandler
#  param:
#    prefix: ice_breadcrumbs_
