seo:
  _config:
    separator: ' - '
    appendTitle: ''

#  collection:
#    collectible:
#      title: %Name%
#      description: test description multirow with some text just for the test
#      keywords: test, title, description, other keyword
#      model: true
